In [26]:
import os
from dotenv import load_dotenv
import sqlalchemy
from typing import List
from sqlalchemy import update, MetaData, func
from sqlalchemy.sql import extract
from datetime import datetime
from sqlalchemy.ext.declarative import declarative_base
import calendar
import pandas as pd

In [27]:
load_dotenv()

_DATABASE_URL = os.getenv("DATABASE_URL")
_DATABASE_URL = _DATABASE_URL.replace("postgres://", "postgresql://")

_engine = sqlalchemy.create_engine(_DATABASE_URL)
Base = declarative_base()

/var/folders/k5/dypr5w717812lzxw05syfj940000gn/T/ipykernel_15956/2870203468.py:7: MovedIn20Warning: The ``declarative_base()`` function is now available as sqlalchemy.orm.declarative_base(). (deprecated since: 2.0) (Background on SQLAlchemy 2.0 at: https://sqlalche.me/e/b8d9)
  Base = declarative_base()

In [28]:

class t_master_db(Base):
    __tablename__ = "master_db"

    client_id = sqlalchemy.Column(sqlalchemy.String, primary_key=True)

    last_name = sqlalchemy.Column(sqlalchemy.String)
    first_name = sqlalchemy.Column(sqlalchemy.String)
    middle_initial = sqlalchemy.Column(sqlalchemy.String)
    total_family_members = sqlalchemy.Column(sqlalchemy.Integer)
    case_manager_initials = sqlalchemy.Column(sqlalchemy.String)
    empowerOR = sqlalchemy.Column(sqlalchemy.Integer)
    renewal_date = sqlalchemy.Column(sqlalchemy.String)
    gender_head_of_household = sqlalchemy.Column(sqlalchemy.String)
    head_of_household_date_of_birth = sqlalchemy.Column(sqlalchemy.String)
    household_number_of_adults = sqlalchemy.Column(sqlalchemy.Integer)
    household_number_of_children = sqlalchemy.Column(sqlalchemy.Integer)
    household_number_of_children_under_18 = sqlalchemy.Column(sqlalchemy.Integer)
    additional_family_members_first_name = sqlalchemy.Column(sqlalchemy.String)
    additional_family_members_last_name = sqlalchemy.Column(sqlalchemy.String)
    additional_family_member_middle_initial = sqlalchemy.Column(sqlalchemy.String)
    additional_family_members_date_of_birth = sqlalchemy.Column(sqlalchemy.String)
    city = sqlalchemy.Column(sqlalchemy.String)
    state = sqlalchemy.Column(sqlalchemy.String)
    zip_code = sqlalchemy.Column(sqlalchemy.String)
    country_of_origin = sqlalchemy.Column(sqlalchemy.String)
    residence_hightstown = sqlalchemy.Column(sqlalchemy.Integer)
    residence_east_windsor = sqlalchemy.Column(sqlalchemy.Integer)
    residence_cranbury = sqlalchemy.Column(sqlalchemy.Integer)
    residence_other = sqlalchemy.Column(sqlalchemy.Integer)
    housing_own = sqlalchemy.Column(sqlalchemy.Integer)
    housing_rent = sqlalchemy.Column(sqlalchemy.Integer)
    housing_other_permanent = sqlalchemy.Column(sqlalchemy.Integer)
    homeless = sqlalchemy.Column(sqlalchemy.Integer)
    date_file_opened = sqlalchemy.Column(sqlalchemy.String)
    renewal_return_date = sqlalchemy.Column(sqlalchemy.String)
    return_client = sqlalchemy.Column(sqlalchemy.Integer)
    new_client = sqlalchemy.Column(sqlalchemy.Integer)
    new_client_intake_date = sqlalchemy.Column(sqlalchemy.String)
    phone_number = sqlalchemy.Column(sqlalchemy.String)
    affected_by_covid = sqlalchemy.Column(sqlalchemy.Integer)
    household_single = sqlalchemy.Column(sqlalchemy.Integer)
    household_two_adults_no_children = sqlalchemy.Column(sqlalchemy.Integer)
    household_single_parent_female = sqlalchemy.Column(sqlalchemy.Integer)
    household_single_parent_male = sqlalchemy.Column(sqlalchemy.Integer)
    household_two_parent = sqlalchemy.Column(sqlalchemy.Integer)
    household_non_related_adults_no_children = sqlalchemy.Column(sqlalchemy.Integer)
    household_multi_generational = sqlalchemy.Column(sqlalchemy.Integer)
    household_other = sqlalchemy.Column(sqlalchemy.Integer)
    household_not_reported = sqlalchemy.Column(sqlalchemy.Integer)
    ethnicity_hispanic_latino = sqlalchemy.Column(sqlalchemy.Integer)
    ethnicity_non_hispanic_latino = sqlalchemy.Column(sqlalchemy.Integer)
    ethnicity_unknown = sqlalchemy.Column(sqlalchemy.Integer)
    ethnicity_american_indian = sqlalchemy.Column(sqlalchemy.Integer)
    ethnicity_alaska_native = sqlalchemy.Column(sqlalchemy.Integer)
    ethnicity_asian = sqlalchemy.Column(sqlalchemy.Integer)
    ethnicity_black_african = sqlalchemy.Column(sqlalchemy.Integer)
    ethnicity_white = sqlalchemy.Column(sqlalchemy.Integer)
    ethnicity_other =  sqlalchemy.Column(sqlalchemy.Integer)
    ethnicity_multi_race = sqlalchemy.Column(sqlalchemy.Integer)
    ethnicity_unknown_not_reported = sqlalchemy.Column(sqlalchemy.Integer)
    adults_in_household_female = sqlalchemy.Column(sqlalchemy.Integer)
    adults_in_household_pregnant_female = sqlalchemy.Column(sqlalchemy.Integer)
    adults_in_household_pregnant_due_date = sqlalchemy.Column(sqlalchemy.String)
    adults_in_household_male = sqlalchemy.Column(sqlalchemy.Integer)
    adults_in_household_other = sqlalchemy.Column(sqlalchemy.Integer)
    adults_in_household_unknown_not_reported = sqlalchemy.Column(sqlalchemy.Integer)
    adults_in_household_disabled = sqlalchemy.Column(sqlalchemy.Integer)
    adults_in_household_aged = sqlalchemy.Column(sqlalchemy.Integer)
    adults_in_household_veteran = sqlalchemy.Column(sqlalchemy.Integer)
    adults_in_household_veteran_active = sqlalchemy.Column(sqlalchemy.Integer)
    household_total_number_of_children = sqlalchemy.Column(sqlalchemy.Integer)
    household_total_number_of_female_children = sqlalchemy.Column(sqlalchemy.Integer)
    household_total_number_of_male_children = sqlalchemy.Column(sqlalchemy.Integer)
    household_total_number_of_disabled_children = sqlalchemy.Column(sqlalchemy.Integer)
    household_children_0_5_years_old = sqlalchemy.Column(sqlalchemy.Integer)
    household_children_6_13_years_old = sqlalchemy.Column(sqlalchemy.Integer)
    household_children_14_17_years_old = sqlalchemy.Column(sqlalchemy.Integer)
    education_9_12_grade_non_graduate = sqlalchemy.Column(sqlalchemy.Integer)
    education_graduate_or_equivalent_diploma = sqlalchemy.Column(sqlalchemy.Integer)
    education_12th_grade_and_some_post_secondary_school = sqlalchemy.Column(sqlalchemy.Integer)
    education_2_4_year_college_graduate = sqlalchemy.Column(sqlalchemy.Integer)
    education_graduate_and_post_secondary_school = sqlalchemy.Column(sqlalchemy.Integer)
    education_graduate_and_post_secondary_school_over_25_years_old = sqlalchemy.Column(sqlalchemy.Integer)
    annual_income = sqlalchemy.Column(sqlalchemy.Integer)
    full_time_employment = sqlalchemy.Column(sqlalchemy.Integer)
    part_time_employment = sqlalchemy.Column(sqlalchemy.Integer)
    migrant_or_seasonal_worker = sqlalchemy.Column(sqlalchemy.Integer)
    unemployed_short_term_6_months_or_less = sqlalchemy.Column(sqlalchemy.Integer)
    unemployed_long_term_over_6_months = sqlalchemy.Column(sqlalchemy.Integer)
    not_in_labor_force = sqlalchemy.Column(sqlalchemy.Integer)
    retired = sqlalchemy.Column(sqlalchemy.Integer)
    unknown_or_not_reported_employment = sqlalchemy.Column(sqlalchemy.Integer)
    obtained_job_through_rise = sqlalchemy.Column(sqlalchemy.Integer)
    poverty_guidelines_125 = sqlalchemy.Column(sqlalchemy.Integer)
    poverty_guidelines_185 = sqlalchemy.Column(sqlalchemy.Integer)
    poverty_guidelines_200 = sqlalchemy.Column(sqlalchemy.Integer)
    poverty_guidelines_over_200 = sqlalchemy.Column(sqlalchemy.Integer)
    total_family_receiving_fs_snap = sqlalchemy.Column(sqlalchemy.Integer)
    total_family_receiving_tanf = sqlalchemy.Column(sqlalchemy.Integer)
    total_family_receiving_alimony = sqlalchemy.Column(sqlalchemy.Integer)
    total_family_receiving_lheap = sqlalchemy.Column(sqlalchemy.Integer)
    total_family_receiving_ga = sqlalchemy.Column(sqlalchemy.Integer)
    total_family_receiving_medicaid_njfc = sqlalchemy.Column(sqlalchemy.Integer)
    total_family_receiving_child_support = sqlalchemy.Column(sqlalchemy.Integer)
    total_family_receiving_pension = sqlalchemy.Column(sqlalchemy.Integer)
    total_family_receiving_ssa = sqlalchemy.Column(sqlalchemy.Integer)
    total_family_receiving_ssi = sqlalchemy.Column(sqlalchemy.Integer)
    total_family_receiving_ssdi = sqlalchemy.Column(sqlalchemy.Integer)
    total_family_receiving_wic = sqlalchemy.Column(sqlalchemy.Integer)
    total_family_receiving_workers_comp = sqlalchemy.Column(sqlalchemy.Integer)
    total_family_receiving_temporary_disability = sqlalchemy.Column(sqlalchemy.Integer)
    total_family_receiving_unemployment = sqlalchemy.Column(sqlalchemy.Integer)

    transactional_id = sqlalchemy.Column(sqlalchemy.Integer)

class t_client(Base):
    __tablename__ = "transactional_db"
    first_name = sqlalchemy.Column(sqlalchemy.String)
    last_name = sqlalchemy.Column(sqlalchemy.String)
    phone = sqlalchemy.Column(sqlalchemy.String)
    dob = sqlalchemy.Column(sqlalchemy.String)
    client_type = sqlalchemy.Column(sqlalchemy.String)
    client_id = sqlalchemy.Column(sqlalchemy.String)

    # PRIMARY KEY to identify instances in transactional_db table
    transactional_id = sqlalchemy.Column(sqlalchemy.Integer, primary_key= True, autoincrement=True)

class t_history(Base):
    __tablename__ = "transactional_history"
    t_id = sqlalchemy.Column(sqlalchemy.Integer)
    client_type = sqlalchemy.Column(sqlalchemy.String)

    visit_date = sqlalchemy.Column(sqlalchemy.Date)
    food_bags = sqlalchemy.Column(sqlalchemy.Integer)
    baby_supplies = sqlalchemy.Column(sqlalchemy.Integer)
    pet_food = sqlalchemy.Column(sqlalchemy.Integer)
    gift_items = sqlalchemy.Column(sqlalchemy.Integer)
    cleaning = sqlalchemy.Column(sqlalchemy.Integer)
    personal_care = sqlalchemy.Column(sqlalchemy.Integer)
    summer_feeding = sqlalchemy.Column(sqlalchemy.Integer)
    pj = sqlalchemy.Column(sqlalchemy.Integer)
    winter = sqlalchemy.Column(sqlalchemy.Integer)
    clothing = sqlalchemy.Column(sqlalchemy.Integer)
    other = sqlalchemy.Column(sqlalchemy.Integer)
    
    # PRIMARY KEY to identify instances in transactional_history table
    visit_id = sqlalchemy.Column(sqlalchemy.Integer, primary_key= True, autoincrement=True)

In [29]:
query = "SELECT * FROM master_db"

In [49]:
df = pd.read_sql(query, _engine)

In [50]:
def format_column_name(col_name):
    formatted_name = ' '.join(word.capitalize() for word in col_name.replace('_', ' ').split())
    if formatted_name == "Client Id":
        return "Client Id (TEFAP)"
    if formatted_name == "Empoweror":
        return "EmpowerOR"
    return formatted_name

In [51]:
# Assuming 'df' is your DataFrame
df.columns = [format_column_name(col) for col in df.columns]

In [52]:
df

,Client Id (TEFAP),Last Name,First Name,Middle Initial,Total Family Members,Case Manager Initials,EmpowerOR,Renewal Date,Gender Head Of Household,Head Of Household Date Of Birth,...,Total Family Receiving Child Support,Total Family Receiving Pension,Total Family Receiving Ssa,Total Family Receiving Ssi,Total Family Receiving Ssdi,Total Family Receiving Wic,Total Family Receiving Workers Comp,Total Family Receiving Temporary Disability,Total Family Receiving Unemployment,Transactional Id
0,T2121,Jocelyn,Quack,J,0,NJ,1,2024-04-11,M,2024-04-09,...,0,0,0,0,0,0,0,0,0,NaN
1,be1231,Grace,Yang,N,0,NJ,1,2024-04-20,Male,2024-04-03,...,0,0,0,0,0,0,0,0,0,23.0

In [18]:
from openpyxl import Workbook
from openpyxl.utils.dataframe import dataframe_to_rows
from openpyxl.styles import Font, Alignment

# Create a new Excel workbook and select the active worksheet
wb = Workbook()
ws = wb.active

# Load data into the Excel worksheet
for r in dataframe_to_rows(df, index=False, header=True):
    ws.append(r)

# Apply formatting similar to your provided template
for cell in ws["1:1"]:  # Assuming the first row contains headers
    cell.font = Font(bold=True)
    cell.alignment = Alignment(horizontal="center")

# Set column widths (example)
ws.column_dimensions['A'].width = 20  # Adjust the width as necessary

# Save the workbook
wb.save('datatest/Formatted_MasterDB_Data.xlsx')

In [48]:
from openpyxl import Workbook
from openpyxl.utils.dataframe import dataframe_to_rows
from openpyxl.styles import Font, Alignment
import pandas as pd

# Assuming 'df' is your DataFrame ready to export
wb = Workbook()
ws = wb.active

# Setup merged headers for "CITY/TOWN" and "HOUSING"
# CITY/TOWN from columns V to Y
ws.append([''] * 21 + ['CITY/TOWN', '', '', ''] + ['HOUSING', '', '', ''] + ['']*2 + ['Total return and new client', '', ''] + ['']*2)
ws.merge_cells(start_row=1, start_column=22, end_row=1, end_column=25)  # Columns V to Y for CITY/TOWN
ws.merge_cells(start_row=1, start_column=26, end_row=1, end_column=29)  # Columns Z to AC for HOUSING
ws.merge_cells(start_row=1, start_column=32, end_row=1, end_column=34)  # Columns AH to AH for New Client
ws.merge_cells(start_row=1, start_column=37, end_row=1, end_column=45)  # Columns AK to AS for Household Level Characteristics
ws.merge_cells(start_row=1, start_column=46, end_row=1, end_column=56)  # Columns 46 to 56 for Ethnicity
ws['V1'].alignment = ws['Z1'].alignment = Alignment(horizontal='center', vertical='center')
ws['V1'].font = ws['Z1'].font = Font(bold=True)

# Set the next row for data headers
header_row = 2

# Add DataFrame headers and format them
for col_idx, column_title in enumerate(df.columns, start=1):
    ws.cell(row=header_row, column=col_idx, value=column_title).font = Font(bold=True)
    ws.cell(row=header_row, column=col_idx).alignment = Alignment(horizontal='center')

# Add data rows starting from the next available row
data_start_row = header_row + 1
for r in dataframe_to_rows(df, index=False, header=False):
    ws.append(r)

# Add sum row immediately after the header row if the column is numerical
sum_row = header_row + 1
ws.insert_rows(sum_row)

for col_idx, col in enumerate(df.columns, start=1):
    if pd.api.types.is_numeric_dtype(df[col]):  # Check if the column is numeric
        # Calculate the sum and add it to the new row
        sum_value = df[col].sum()
        ws.cell(row=sum_row, column=col_idx, value=sum_value)

# Apply formatting to sum row
for cell in ws[sum_row]:
    cell.font = Font(bold=True)
    cell.number_format = '#,##0'  # Change format as necessary
    
#Set wrap text for all cells
for row in ws.iter_rows():
    for cell in row:
        cell.alignment = Alignment(wrap_text=True)
        
# Set the height of the first row
ws.row_dimensions[1].height = 30  # Adjust the height as needed

# Save the workbook
file_path = 'datatest/Formatted_MasterDB_Data2.xlsx'
wb.save(file_path)

print(f"File saved to {file_path}")

File saved to datatest/Formatted_MasterDB_Data2.xlsx